name: skill_swap
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider_plus: ^7.1.1
  iconsax: 0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  lottie: ^3.1.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/images/onboarding_images/

# ğŸ‘‡ Ø¶ÙŠÙ Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø§Ù„Ø³Ø¨Ù„Ù‘Ø§Ø´ Ù‡Ù†Ø§ (ÙÙŠ Ù†ÙØ³ Ø§Ù„Ù…Ù„Ù)
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logo/skillswap_logo.png
  image_dark: assets/logo/skillswap_logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logo/skillswap_logo.png
    image_dark: assets/logo/skillswap_logo.png

  web: true
